name: Build and Push to GHCR

on:
  push:
    paths:
      - 'Dockerfile'  # Only run if Dockerfile changes
  workflow_dispatch:  # Manual trigger
  # schedule:
  #   - cron: '0 0 * * *' # Uncomment for daily check (10 AM AEST)

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write      # Needed to commit build_marker and last_digest.txt
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # ----------------------------
      # Optional: Automatically Update N8N with Version Digest Check (commented)
      # ----------------------------
      # - name: Install jq for JSON parsing
      #   run: sudo apt-get update && sudo apt-get install -y jq

      # - name: Check n8n version digest
      #   id: check_version
      #   run: |
      #     LATEST_DIGEST=$(docker manifest inspect docker.n8n.io/n8nio/n8n:latest | jq -r '.manifests[0].digest')
      #     echo "Latest n8n digest: $LATEST_DIGEST"
      #     echo "LAST_DIGEST=$(cat last_digest.txt 2>/dev/null || echo '')" >> $GITHUB_ENV
      #     if [ "$LAST_DIGEST" != "$LATEST_DIGEST" ]; then
      #       echo "New n8n version detected."
      #       echo "$LATEST_DIGEST" > last_digest.txt
      #       echo "BUILD=true" >> $GITHUB_ENV
      #       date > build_marker.txt
      #     else
      #       echo "No new version detected."
      #       echo "BUILD=false" >> $GITHUB_ENV
      #     fi

      # - name: Commit version marker
      #   if: env.BUILD == 'true'
      #   run: |
      #     git config user.name "GitHub Actions"
      #     git config user.email "actions@github.com"
      #     git add last_digest.txt build_marker.txt
      #     git commit -m "Update build marker and digest" || echo "Nothing to commit"
      #     git push

      # ----------------------------
      # Free space
      # ----------------------------
      - name: Free up disk space (GitHub action)
        uses: kfir4444/free-disk-space@main
        with:
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          tool-cache: true
          swap-storage: true

      - name: Manual cleanup
        run: |
          sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/lib/android
          docker system prune -a -f
          docker builder prune -a -f

      # ----------------------------
      # Docker Setup & Login
      # ----------------------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # ----------------------------
      # Build and Push Image
      # ----------------------------
      - name: Build and push Docker image
        # if: env.BUILD == 'true'  # Uncomment to trigger only on version change
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/n8n-gpu:latest
          provenance: false
          cache-from: type=gha,mode=min,ignore-error=true
          cache-to: type=gha,mode=min,ignore-error=true
