name: Build and Push to GHCR

on:
  push:
    paths:
      - 'Dockerfile'  # Only run if Dockerfile changes
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # No larger runners available on GitHub-hosted runners

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # Free space using GitHub Action
      - name: Free up disk space (GitHub action)
        uses: kfir4444/free-disk-space@main
        with:
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          tool-cache: true
          swap-storage: true

      # Additional manual cleanup
      - name: Manual cleanup (remove heavy dirs + Docker cache)
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/lib/android
          docker system prune -a -f
          docker builder prune -a -f

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/n8n-gpu:latest
          provenance: false
          cache-from: type=gha,mode=min,ignore-error=true
          cache-to: type=gha,mode=min,ignore-error=true
