name: Build and Push to GHCR

on:
  push:
    paths:
      - 'Dockerfile'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Free up disk space (~20–30 GB)
        uses: kfir4444/free-disk-space@main
        with:
          android: true
          dotnet: true
          haskell: true
          swap-storage: true
          docker-images: true
          large-packages: true
          tool-cache: true

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/n8n-gpu:latest
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=min,ignore-error=true
