name: Build and Push to GHCR

on:
  push:
    paths:
      - 'Dockerfile'        # ⬅️ Only trigger when this file changes
  workflow_dispatch:        # ⬅️ Allow manual trigger from Actions tab

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/n8n-gpu:latest
          provenance: false                # Disable SBOM/attestation to reduce overhead
          cache-from: type=gha
          cache-to: type=gha,mode=max
