name: Build and Push to GHCR

on:
  workflow_dispatch:  # ✅ Manual trigger only — avoids triggering on every push

jobs:
  build-and-push:
    name: Build and Stream to GHCR
    runs-on: ubuntu-latest-xl  # ✅ Larger runner to avoid disk overflow

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # for caching and image tagging context

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          load: false                   # ✅ Don’t save image locally
          compress: true                # ✅ Reduce build size on push
          provenance: false             # ✅ Skip provenance metadata to reduce output
          no-cache: false               # Set true if you're debugging or testing cache issues
          tags: ghcr.io/noosa4567/n8n-gpu:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
