name: Build and Push to GHCR

on:
  push:
    paths:
      - 'Dockerfile'               # ✅ Only run if Dockerfile changes
  workflow_dispatch:              # ✅ Allow manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-22.04         # ✅ More disk space than ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Optional cleanup: reclaim 10–20 GB
      - name: Free up disk space
        uses: kfir4444/free-disk-space@main
        with:
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          tool-cache: true
          swap-storage: true

      # Manual Docker cleanup
      - name: Prune Docker system
        run: |
          docker builder prune --all --force
          docker system prune --all --force

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          no-cache: true                       # ✅ Prevent layer bloat
          tags: ghcr.io/${{ github.repository_owner }}/n8n-gpu:latest
          provenance: false                    # ✅ Disable SBOM to reduce overhead
          cache-from: type=gha
          cache-to: type=gha,mode=min,ignore-error=true  # ✅ Smaller cache, non-blocking
